name: CI — Lint & Smoke Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install "black[jupyter]==23.9.1" flake8==6.1.0 numpy pillow
          pip install -e .

      - name: Run Black (check only)
        run: black --check .

      - name: Run Flake8
        run: flake8 --max-line-length=100 .

      - name: Run smoke test
        run: python scripts/smoke_test.py
