name: CI — Lint & Smoke Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install lightweight dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.9.1 flake8==6.1.0 numpy pillow

      - name: Run Black (check only)
        run: black --check .

      - name: Run Flake8
        run: flake8 --max-line-length=100 .

      - name: Run smoke test
        run: python scripts/smoke_test.py
